version: "3"

services: 
  backend: 
    build: 
      context: ./backend
      dockerfile: ./Dockerfile
    image: "lucasv/simplewebscrapper"
    ports:
      - "5000:5000"
      

  frontend:
    build: 
      context: ./frontend
      dockerfile: ./Dockerfile
    image: "lucasv/simplereactapp"
    ports:
      - "3000:3000"
    links:
    - "backend:be"

